# Dockerfile
FROM python:3.8-slim

# Set the working directory
WORKDIR /app

# Copy requirements file and install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose a port if you decide to add an API (optional)
EXPOSE 8000

# Set the default command to run the training script
CMD ["python", "src/train.py"]
